{
  "pipe_parallel_size": 0,
  "model_parallel_size": 1,
  "make_vocab_size_divisible_by": 1,

  # model settings
  "num_layers": 32,
  "hidden_size": 4096,
  "num_attention_heads": 32,
  "seq_length": 2048,              # 2048
  "max_position_embeddings": 2048, #  2048
  "pos_emb": "rotary",
  "rotary_pct": 1,
  "no_weight_tying": true,
  "gpt_j_residual": false,
  "output_layer_parallelism": "column",
  "norm": "rmsnorm",
  "rms_norm_epsilon": 1.0e-6,

  "scaled_upper_triang_masked_softmax_fusion": false,
  "bias_gelu_fusion": false,
  "use_bias_in_norms": false,
  "use_bias_in_attn_linear": false,
  "mlp_type": "llama",
  "activation": "silu",

  #"load": "/data1/xxx/llama_exp/llama_neox",
  "load": "checkpoints_llama_test_5e-5_test",
  "save": "checkpoints_llama_fp_tuning",
  "log_dir": "logs_llama_fp_tuning",

  "use_tempnet": true,
  "tempnet_rho": 10.0,

  "tokenizer_type": "SPMTokenizer",
  "vocab_file": "/data1/xxx/llama_exp/llama_weight/tokenizer.model",
  "data_path": "/data1/xxx/llama_exp/llama_data/owt2_spmtoken_text_document",
}
